import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import { Inter } from '@next/font/google'
import NavigationBar from "./components/NavigationBar"

const inter = Inter({ subsets: ['latin'] })

function Card() {
  return (
    <div>
      <a href="#" className="block">
        <img
          alt="Art"
          src="https://media.licdn.com/dms/image/C4E03AQH9Bpk-TwxT1w/profile-displayphoto-shrink_200_200/0/1637614435777?e=1678924800&v=beta&t=63bMN_b4WL7OUnjbbaafmJgfnFR-2o-yYkRhpGlnQ_A"
          className="h-96 w-full object-cover"
        />
        <h3 className="mt-4 text-xl font-bold text-gray-900">Software Engineer</h3>
        <p className="mt-2 max-w-sm text-gray-700">
          I am an aspiring software engineer who attends Colorado State University. I have a degree
          in Physics and am working on a degree in Computer Science. 
          </p>
      </a>
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Will Mingus</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavigationBar />
      <main className="max-w-md mx-auto p-8">
        <div className="block">
          <Card/>
        </div>
      </main>
    </>
  )
}
